name: Publish Hexo to gitpage
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    #- uses: szenius/set-timezone@v1.2
      #with:
        #timezoneLinux: "Asia/Shanghai"
    #- name: Install Node.js
      #uses: actions/setup-node@v3
      #with:
        #node-version: 13.14.0
        #registry-url: "https://registry.npmjs.org"
    - name: Install dependencies
      run: |
        npm install -g hexo-cli
        npm install
    - name: Generate Hexo site
      run: |
        hexo clean
        hexo generate
    - name: Deploy to page repo
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.SECRETS_ARCHIVES }}
        external_repository: chenzhenguo/chenzhenguo.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
